<?php if($this->isEnabled()): ?>
    <script language=javascript>
        (function (w,d,n,u) {
            if(typeof yuzu === "undefined") {
                w[n] = w[n] || function () {(w[n].q = w[n].q || []).push(arguments)};
            }
            var a=d.createElement("script");
            a.type="text/javascript",a.async=1,a.src=u;
            var b=d.getElementsByTagName("script")[0];
            b.parentNode.insertBefore(a,b)
        })(window,document,'yuzu','<?php echo Mage::helper('yuzu_tags')->getConfig('yuzu_tags/general/tag_url_js'); ?>');
    </script>


    <script>
        (function(document) {
            document.addEventListener('DOMContentLoaded', setupTracking);

            var fields = {
                    firstname: 'billing:firstname',
                    lastname: 'billing:lastname',
                    telephone: 'billing:telephone',
                    email: 'billing:email',
                    country: 'billing:country_id'
                };

            function setupTracking () {
                for (var item in fields) {
                    if (fields.hasOwnProperty(item)) {
                        if (Array.isArray(fields[item])) {
                            for (var i = 0; i < fields[item].length; i++) {
                                var el = document.getElementById(fields[item][i]);
                                if (el) {
                                    fields[item] = el;
                                    break;
                                }
                            }
                        } else {
                            fields[item] = document.getElementById(fields[item]);
                        }
                    }
                }
                if (fields.email && fields.firstname) {
                    for (item in fields) {
                        if (fields.hasOwnProperty(item)) {
                            fields[item].addEventListener('blur', trackData);
                        }
                    }
                }
            }

            function collectData () {
                var data = [];
                for (var item in fields) {
                    if (fields.hasOwnProperty(item)) {
                        // Only if email is set
                        if (item === 'email' && fields[item].value === '') {
                            return false;
                        }
                        if (item === 'country') {
                            data.push((encodeURIComponent(item) + "=" + encodeURIComponent(fields[item].options[fields[item].selectedIndex].value)));
                        } else {
                            data.push((encodeURIComponent(item) + "=" + encodeURIComponent(fields[item].value)));
                        }
                    }
                }
                return data;
            }

            function trackData () {
                var data = collectData(),
                trackingURL = typeof yuzu_cartsave_url !== 'undefined' ? yuzu_cartsave_url : '/yuzu/cartsave';
                if (data) {
                    xhr = new XMLHttpRequest();
                    xhr.open('POST', trackingURL, true);
                    xhr.setRequestHeader("Content-type", "application/x-www-form-urlencoded");
                    xhr.send(data.join("&"));
                }
            }
        })(document);

    </script>
<?php endif; ?>